ch_cookie_consent:
    cookie_categories: # Below are the default supported categories
        - 'necessary'
        - 'functional'
        - 'analytics'
        - 'marketing'
    use_logger: true # Logs user actions to database
    http_only: true # Sets HttpOnly on cookies
    form_action: ~ # $routeName # When set, xhr-Requests will only be sent to this route. Take care of having the route available.
    csrf_protection: true # The cookie consent form is csrf protected or not

    # When set, the user will be redirected to this route when rejecting all cookies
    # reject landing page: 'privacy_cookies' or 'privacy_reject'
    reject_route_name: 'privacy_reject'
