parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $useLogger: '%ch_cookie_consent.use_logger%'
            $httpOnly: '%ch_cookie_consent.http_only%'
            #$cookieCategories: '%ch_cookie_consent.cookie_categories%'
            #$formAction: '%ch_cookie_consent.form_action%'
            #$csrfProtection: '%ch_cookie_consent.csrf_protection%'

    ConnectHolland\CookieConsentBundle\:
        resource: '../../'
        exclude:
            - '../../Controller/'
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Tests/'
            - '../../Resources/'
            - '../../CHCookieConsentBundle.php'

    # Controller registration
    # Controller obligatory need to be public
    ConnectHolland\CookieConsentBundle\Controller\CookieConsentController:
        public: true
        arguments:
            $formAction: '%ch_cookie_consent.form_action%'
        tags:
            - { name: 'controller.service_arguments' }

    ConnectHolland\CookieConsentBundle\Form\CookieConsentType:
        arguments:
            $cookieCategories: '%ch_cookie_consent.cookie_categories%'
            $csrfProtection: '%ch_cookie_consent.csrf_protection%'
        tags:
            - { name: form.type }

#    ConnectHolland\CookieConsentBundle\Cookie\CookieChecker:
#        arguments:
#            $requestStack: '@request_stack'

#    ConnectHolland\CookieConsentBundle\Cookie\CookieLogger:
#        arguments:
#            $requestStack: "@request_stack"

#    ConnectHolland\CookieConsentBundle\Twig\CHCookieConsentTwigExtension:
#        arguments:
#            $cookieChecker: '@ConnectHolland\CookieConsentBundle\Cookie\CookieChecker'
